from fastapi import Response
from prometheus_client import CONTENT_TYPE_LATEST, Counter, Histogram, generate_latest

# Metrics
REQUEST_COUNT = Counter(
    "api_requests_total", "Total number of API requests", ["method", "endpoint", "http_status"]
)
REQUEST_LATENCY = Histogram("api_request_latency_seconds", "Latency of API requests", ["endpoint"])
TOKENS_GENERATED = Counter(
    "model_tokens_generated_total", "Total number of tokens generated by the model"
)
INFERENCE_DURATION = Histogram("model_inference_duration_seconds", "Duration of model inference")


def metrics_endpoint() -> Response:
    """
    Returns Prometheus metrics.
    """
    return Response(content=generate_latest(), media_type=CONTENT_TYPE_LATEST)
